name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: v${{ steps.semver.outputs.version }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE|feat!"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}"
          
      - name: Create tag
        if: steps.semver.outputs.version != ''
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git tag v${{ steps.semver.outputs.version }}
          git push origin v${{ steps.semver.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.version != ''
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platform: linux/amd64
          push: true
          tags: |
            rafaspimenta/rinha-backend-csharp:${{ needs.build.outputs.version }}
            rafaspimenta/rinha-backend-csharp:latest